export enum ActionType {
    SEARCH_REPOSITORIES = "SEARCH_REPOSITORIES",
    SEARCH_REPOSITORIES_SUCCESS='SEARCH_REPOSITORIES_SUCCESS',
    SEARCH_REPOSITORIES__ERROR = "SEARCH_REPOSITORIES__ERROR"
}